#!/bin/bash
# script stops on error
set -e

aptPrograms=(vim git)
jetbrains=(pycharm-community webstorm intellij-idea-community)
snaps=(nordpass)

# install programs
apt update
echo "apt update successful"
apt -y install ${aptPrograms[@]}
echo "apt install successful"
echo "installed following packages: ${aptPrograms[@]}"

snap install ${snaps[@]}
echo "snaps installed"
echo "installed following snaps: ${snaps[@]}"

for app in "${jetbrains[@]}"
do
	installApplication="$app --classic"
	snap install $installApplication
done
echo "jetbrain-application installed successful"
echo "installed following jetbrains: ${jetbrains[@]}"

# configurations
git config --global user.name "Danilo Bigovic"
git config --global user.email "d.big.be@gmail.com"
cd ~/Documents
git clone https://github.com/bigBrownBear91/installationScript.git
echo "Git configured and repo installationScript cloned"

snap connect nordpass:password-manager-service
echo "Permissions for NordPass to store security keys locally granted"

firefoxPath="~/.mozilla/firefox"
cp installationScript/profiles.ini "${firefoxPath}/profiles.ini"
echo "Firefox configurations copied successfully"

exit 0
