#!/bin/bash

# define programs which should be installed
aptPrograms=(vim git curl)
#for testing purposes: only install pycharm
#jetbrains=(pycharm-community webstorm intellij-idea-community)
jetbrains=(pycharm-community)
snaps=(nordpass)

# install the programs from the array
apt update -qq
echo "apt update successful"
apt -y install ${aptPrograms[@]}
echo "apt install successful"
echo "installed following packages: ${aptPrograms[@]}"

snap install ${snaps[@]}
echo "snaps installed"
echo "installed following snaps: ${snaps[@]}"

for app in "${jetbrains[@]}"
do
	installApplication="$app --classic"
	snap install $installApplication
done
echo "jetbrain-application installed successful"
echo "installed following jetbrains: ${jetbrains[@]}"

# configurations
git config --global user.name "Danilo Bigovic"
git config --global user.email "d.big.be@gmail.com"
git config --global diff.tool vimdiff
cd ~/Documents
git clone https://github.com/bigBrownBear91/installationScript.git
echo "Git configured and repo installationScript cloned"

snap connect nordpass:password-manager-service
echo "Permissions for NordPass to store security keys locally granted"

firefoxPath="~/.mozilla/firefox"
cp ~/Documents/installationScript/profiles.ini "${firefoxPath}/profiles.ini"
if [ echo "$?" -eq 0 ]; then
	echo "Firefox configurations copied successfully"
else
	echo "Firefox configurations unsuccessful"
fi

# download and execute abaclient
curl https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/2.2.672/abaclient-2.2.672.run --output ~/Downloads/abaclient.run
sh ~/Downloads/abaclient.run
rm Downloads/abaclient.run
echo "Abaclient downloaded and installed"

exit 0
