#!/bin/bash

user="ubuntu"

# define programs which should be installed
aptPrograms=(vim git curl)
#for testing purposes: only install pycharm
#jetbrains=(pycharm-community webstorm intellij-idea-community)
jetbrains=(pycharm-community)
snaps=(nordpass)

# install the programs from the array
apt update -qq
echo "apt update successful"
apt -y install ${aptPrograms[@]}
echo "apt-programs installed successfully"

snap install ${snaps[@]}
echo "snaps installed successfully"

for app in "${jetbrains[@]}"
do
	installApplication="$app --classic"
	snap install $installApplication
done
echo "jetbrain-application installed successfully"

# configurations
git config --global user.name "Danilo Bigovic"
git config --global user.email "d.big.be@gmail.com"
git config --global diff.tool vimdiff

pathToHome="/home/"$user"" # necessary because cd is not possible in sudo
pathToDocuments=""$pathToHome"/Documents" 
pathToDownloads=""$pathToHome"/Downloads"
if [ -d ""$pathToDocuments"/installationScript" ]; then
	echo "Directory installationScript exists already"
else
	git clone https://github.com/bigBrownBear91/installationScript.git "$pathToDocuments"
	echo "Git configured and repo installationScript cloned"
fi

snap connect nordpass:password-manager-service
echo "Permissions for NordPass to store security keys locally granted"

firefoxPath=""$pathToHome"/.mozilla/firefox"
if [ ! -d ""$pathToHome"/.mozilla" ]; then
	mkdir -p "$pathToHome"/.mozilla/firefox
fi
cp "$pathToDocuments"/installationScript/profiles.ini "${firefoxPath}"/profiles.ini
if [ $? -eq 0 ]; then
	echo "Firefox configurations copied successfully"
else
	echo "Firefox configurations unsuccessful"
fi

# download and execute abaclient
which abaclient &> /dev/null
if [ $? -gt 0 ]; then 
	curl https://storage.googleapis.com/images.abasky.net/119676df089a90ab3c3004398806433938052586dcd9a6bcacfb0e3e4024f339/2.2.672/abaclient-2.2.672.run --output /home/"$user"/Downloads/abaclient.run
	sh /home/"$user"/Downloads/abaclient.run
	rm /home/"$user"/Downloads/abaclient.run
	echo "Abaclient downloaded and installed"
else
	echo "Abaclient is already installed"
fi

exit 0
